Workarounds to enable DeepSpeed transformer inference on ROCm
ROCmSoftwarePlatform/DeepSpeed pull request #58
Opened 2023-04-18 18:33 UTC by rraminen

These changes are required to resolve the following errors when running bloom workload:

1. 
```
/opt/conda/lib/python3.8/site-packages/deepspeed/ops/csrc/includes/conversion_utils_hip.h:270:12: error: use of undeclared identifier '__double2half'; did you mean '__double2hiint'?
    return __double2half(val);
           ^~~~~~~~~~~~~
           __double2hiint
/opt/rocm-5.4.0/include/hip/amd_detail/amd_device_functions.h:440:30: note: '__double2hiint' declared here
__device__ static inline int __double2hiint(double x) {
                             ^
```

2.
```
 /opt/conda/lib/python3.8/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/apply_rotary_pos_emb.hip:195:48: error: use of undeclared identifier '__shfl_sync'
            auto q_rot_tmp = lane < half_dim ? __shfl_sync(mask[lane], q_rot, lane + half_dim)

```

3. 
```
/opt/conda/lib/python3.8/site-packages/deepspeed/ops/csrc/includes/reduction_utils_hip.h:278:43: error: excess elements in struct initializer
    constexpr __half2_raw zero = {0x0000, 0x0000};
                                          ^~~~~~

```

2023-04-19 16:47 UTC, jeffdaily commented on csrc/includes/reduction_utils.h
> +    constexpr __half2_raw zero = {0x0000};
```suggestion
    constexpr __half2_raw zero2 = {_Float16_2{0x0000,0x0000}};
```

2023-04-19 16:48 UTC, jeffdaily commented on csrc/includes/reduction_utils.h
> +    constexpr __half2_raw inf = {0x7C00};
```suggestion
    constexpr __half2_raw inf = {_Float16_2{0x7C00,0x7C00}};
```

2023-04-19 16:48 UTC, jeffdaily commented on csrc/includes/reduction_utils.h
> +    constexpr __half2_raw neg_inf = {0xFC00};
```suggestion
    constexpr __half2_raw zero2 = {_Float16_2{0xFC00,0xFC00}};
```

2023-04-19 17:01 UTC, jeffdaily commented on csrc/transformer/inference/csrc/apply_rotary_pos_emb.cu
> +                                             : __shfl(mask[lane], k_rot, lane - half_dim);
```suggestion
            auto q_rot_tmp = lane < half_dim ? __shfl(q_rot, lane + half_dim)
                                             : __shfl(q_rot, lane - half_dim);
            auto k_rot_tmp = lane < half_dim ? __shfl(k_rot, lane + half_dim)
                                             : __shfl(k_rot, lane - half_dim);
```
The function signature for __shfl is

`__device__ inline int __shfl(int var, int src_lane, int width = warpSize);`

2023-04-19 17:01 UTC, jeffdaily requested changes
Please address all suggested changes.  Thanks.

2023-04-19 21:02 UTC, rraminen commented on csrc/includes/reduction_utils.h
> +    constexpr __half2_raw inf = {0x7C00};
Made the suggested change

2023-04-28 15:45 UTC, rraminen commented
Use https://github.com/ROCmSoftwarePlatform/DeepSpeed/tree/transformer_inference branch which contains the changes mentioned in this PR

Closing this PR as we have the below two merged
1. https://github.com/ROCmSoftwarePlatform/DeepSpeed/pull/59
2. https://github.com/ROCmSoftwarePlatform/DeepSpeed/pull/60

2023-04-28 15:45 UTC, closed without merging